/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Greeter } from "./Greeter";
export type { Greeter2 } from "./Greeter2";

export { Greeter__factory } from "./factories/Greeter__factory";
export { Greeter2__factory } from "./factories/Greeter2__factory";
